"""Wraps pytest (+ pytest-cov) and parses its JUnit/coverage XML output.

No test-detection magic here: we shell out to the real tool and parse its
own report format, so Agent 3 never has to reimplement test collection.
"""

import shutil
import subprocess
from pathlib import Path

# defusedxml, not the stdlib xml.etree.ElementTree: these XML reports are
# generated by pytest/coverage locally, but Agent 3's own mission is
# catching exactly this class of issue (bandit S314) -- parsing XML with
# the stdlib parser is vulnerable to XXE/billion-laughs if the report file
# were ever tampered with (e.g. a compromised CI runner or dependency).
import defusedxml.ElementTree as ET

from agent3_security_quality.core.errors import ScannerExecutionError, ScannerUnavailableError
from agent3_security_quality.core.schemas import TestResults


def _parse_junit(junit_path: Path) -> tuple[int, int, int, int]:
    root = ET.parse(junit_path).getroot()
    suite = root if root.tag == "testsuite" else root.find("testsuite")
    if suite is None:
        raise ScannerExecutionError(f"no <testsuite> element found in {junit_path}")

    total = int(suite.get("tests", 0))
    failures = int(suite.get("failures", 0))
    errors = int(suite.get("errors", 0))
    skipped = int(suite.get("skipped", 0))
    failed = failures + errors
    passed = total - failed - skipped
    return total, passed, failed, skipped


def _parse_coverage(coverage_path: Path) -> float:
    if not coverage_path.exists():
        return 0.0
    root = ET.parse(coverage_path).getroot()
    line_rate = root.get("line-rate")
    return round(float(line_rate) * 100, 1) if line_rate is not None else 0.0


def run(
    target: str,
    *,
    cov_source: str | None = None,
    junit_path: str = "pytest-junit.xml",
    coverage_path: str = "coverage.xml",
) -> TestResults:
    """Run pytest against `target`, returning structured TestResults.

    `cov_source` enables coverage measurement for that package/path; when
    omitted, coverage_pct is reported as 0.0 rather than guessed.
    """
    if shutil.which("pytest") is None:
        raise ScannerUnavailableError("pytest is not installed")

    cmd = ["pytest", target, "-q", f"--junitxml={junit_path}"]
    if cov_source:
        cmd += [f"--cov={cov_source}", f"--cov-report=xml:{coverage_path}"]

    result = subprocess.run(cmd, capture_output=True, text=True)

    junit_file = Path(junit_path)
    if not junit_file.exists():
        raise ScannerExecutionError(
            f"pytest did not produce a junit report (exit {result.returncode}):\n"
            f"{result.stdout}\n{result.stderr}"
        )

    total, passed, failed, skipped = _parse_junit(junit_file)
    coverage_pct = _parse_coverage(Path(coverage_path)) if cov_source else 0.0

    return TestResults(
        total=total,
        passed=passed,
        failed=failed,
        skipped=skipped,
        coverage_pct=coverage_pct,
        flaky_detected=0,  # TODO(phase 3): needs multi-run history, not a single pass
    )
